### ISSUE TITLE
Step 1 Error

### ISSUE THREAD

**Issue by caldera1** [DiUS/pact-workshop-jvm#12]
Hello,
The error is:

#gradle :providers:drop-wizard:run

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':providers:springboot-provider'.
> No signature of method: org.gradle.util.NameValidator.asValidName() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [pactVerify_Our_Provider]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

All help will be well received.

Thank you.

**Comment by martinschneider** [comment]
How did you resolve this? I am facing the exact same issue with the [latest master](https://github.com/DiUS/pact-workshop-jvm/tree/b50871c2aaa709c7b77f81c3e97c01c57b9143ad) and Gradle 6.1.1.
