### ISSUE TITLE
Error on step3

### ISSUE THREAD

**Issue by nicopaez** [DiUS/pact-workshop-jvm#13]
After executing step 1 and 2 successfully, I am getting the following error (I am running on Mac and Java8):

./gradlew :consumer:check

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':consumer:testCompileClasspath'.
> Could not find groovy-all-indy.jar (org.codehaus.groovy:groovy-all:2.4.12).
  Searched in the following locations:
      file:/Users/nicopaez/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12-indy.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by ghost** [comment]
@nicopaez Have you managed to fix this issue? I am running into the exact same error.

**Comment by neugartf** [comment]
Running in the same issue

**Comment by uglyog** [comment]
I've updated it to use Java and JUnit 4 for the test. Groovy JARs are no longer needed.
