### ISSUE TITLE
Error in import 

### ISSUE THREAD

**Issue by Blankofnothing** [DiUS/pact-workshop-jvm#14]
I  use eclipse to import the workshop,then I got this error:

Could not run build action using Gradle installation 'D:\ThirdParty\gradle-4.10.1'.
A problem occurred configuring project ':providers:springboot-provider'.
No signature of method: org.gradle.util.NameValidator.asValidName() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [pactVerify_Our_Provider]

Does anyone get the same error with me ?
I try to follow this opearation,but didn't work.
https://stackoverflow.com/questions/27951027/errorcould-not-run-build-action-using-gradle-installation-c-program-files-and

Do I  miss something?

Thanks in advanced!

**Comment by uglyog** [comment]
I would recommend using IntelliJ IDEA. The community version is free and works with this project.
