### ISSUE TITLE
Unable to start the provider in Step 1. Getting error Address already in use

### ISSUE THREAD

**Issue by blackfalcon03** [DiUS/pact-workshop-jvm#15]
While running the command in Windows 10

$ ./gradlew :providers:dropwizard-provider:run

I get the error that the Address is already in use and the build fails. How can i correct this?

**Comment by bedla** [comment]
Something is running on same port (8080) as provider is trying to start.
You can use TCPView (https://docs.microsoft.com/cs-cz/sysinternals/downloads/tcpview) to find that process on port 8080.
This issues could be closed imo :)
