### ISSUE TITLE
How to send SSL certificates to validate the provider service in pact

### ISSUE THREAD

**Issue by Hidayath-S** [DiUS/pact-workshop-jvm#16]
I have created the pact file with all the request, headers and response details. When i try to hit my service using HttpTarget it throws "handshake failure" exception. How can i send the SSL file and password?. Is it possible to add in pact file or do we have any other solution for this.

Need help ASAP.

Regards,
Hidayath

**Comment by uglyog** [comment]
This does not seem to be related to this workshop? HttpsTarget needs to be used for HTTPS instead of HttpTarget.
