### ISSUE TITLE
Step 4 error

### ISSUE THREAD

**Issue by martinschneider** [DiUS/pact-workshop-jvm#17]
I am receiving the exact same error as described in [this issue](https://github.com/DiUS/pact-workshop-jvm/issues/12) but at a later step.

Steps 1 to 3 work fine, the error occurs from Step 4 onwards:

```
A problem occurred configuring project ':providers:springboot-provider'.
> No signature of method: org.gradle.util.NameValidator.asValidName() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [pactVerify_Our_Provider]
```

My Gradle version is 6.1.1.

**Comment by uglyog** [comment]
I've updated it to use Pact-JVM 4.1.2.
