### ISSUE TITLE
Step 1 error "Could not determine java version from '11.0.2" when using ./gradlew

### ISSUE THREAD

**Issue by sasconsul** [DiUS/pact-workshop-jvm#19]
I got an error when looking into pact.  [BTW:why is gradle looking for version 4.6 when 6.5.1 is available?  Haven't folks updated to the newer Gradle verions?]

Here is a transcript of what I did:

% ./gradlew :providers:dropwizard-provider:run
Downloading https://services.gradle.org/distributions/gradle-4.6-all.zip
...<lots of dots>...
Unzipping /Users/sasconsul/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6-all.zip to /Users/sasconsul/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg
Set executable permissions for: /Users/sasconsul/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
sasconsul@Stuarts-MBP pact-workshop-jvm % java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by sasconsul** [comment]
Got the step working when I used :
`gradle :providers:dropwizard-provider:run`

But, there are many errors in the log before the application starts.

**Comment by jogaco** [comment]
Lots of exceptions on Java 11, but no exceptions on Java 8

**Comment by uglyog** [comment]
I've upgraded Gradle to 6.6.1, which works with Java 11
