### ISSUE TITLE
pactPublish error when I am on step13

### ISSUE THREAD

**Issue by yuqitao** [DiUS/pact-workshop-jvm#2]
yu@ubuntu:~/pact-workshop-jvm$ ./gradlew consumer:pactPublish
:consumer:pactPublish
Publishing Our Little Consumer-Our Provider.json ... FAILED! 401 Unauthorized - Unknown error
:consumer:pactPublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
One or more of the pact files were rejected by the pact broker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.734 secs

**Comment by yuqitao** [comment]
need I do this in file gradle.properties :
actBrokerUser=pactBrokerUser
pactBrokerPassword=pactBrokerPassword

**Comment by yuqitao** [comment]
after do this , there is still an error like :
yu@ubuntu:~/pact-workshop-jvm$ ./gradlew consumer:pactPublish
FAILURE: Build failed with an exception.

* Where:
Build file '/home/yu/pact-workshop-jvm/providers/springboot-provider/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':providers:springboot-provider'.
> Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.391 secs

**Comment by yuqitao** [comment]
i know i must sign up on website : https://pact.dius.com.au/register
can I deploy my own service as a broker like this ?

**Comment by uglyog** [comment]
You can use your own broker, you don't need to signup for one. You can run one using docker, just search on docker hub.

You will have to setup the appropriate values in https://github.com/DiUS/pact-workshop-jvm/blob/master/providers/springboot-provider/build.gradle#L46 and https://github.com/DiUS/pact-workshop-jvm/blob/master/providers/dropwizard-provider/src/test/groovy/au/com/dius/pactworkshop/dropwizardprovider/PactVerificationTest.groovy#L19 to match the pact broker you are running

**Comment by yuqitao** [comment]
i know , thank you very much
