### ISSUE TITLE
What users and password to use ?

### ISSUE THREAD

**Issue by ccristian** [DiUS/pact-workshop-jvm#6]
pactBrokerPassword 
pactBrokerUser 

As i see it connects to https://test.pact.dius.com.au

Is there a way to create a test user of our own ? 

Do we need it to run the samples ?

Thanks

**Comment by uglyog** [comment]
You can sign up for a broker of your own at www.pact.dius.com.au, or you can run your own instance in a docker container. If you do signup, just put this workshop as the reference.

**Comment by bedla** [comment]
~I have been redirected to pactflow.io and registered there for free plan. but credentials i have choosen does not work. What am I doing wrong?~
Thx Ivos

What I found:
- pactflow allows auth token only
- token can be generated in administration
- than I have to change pact broker URL and authentication

for java tests
```
@PactBroker(host = "ivosmid.pactflow.io", scheme = "https", port = "443",
  authentication = @PactBrokerAuth(token = "token-here"))
```

and for gradle scripts
```
pact {
  publish {
    pactBrokerUrl = 'https://ivosmid.pactflow.io'
    pactBrokerToken = 'token-here'
    tags = ['test']
  }
}
```

**Comment by uglyog** [comment]
Step 13 has been updated to run against a Pact Broker in a docker container
