### ISSUE TITLE
Project doesn't publish verification back to the broker

### ISSUE THREAD

**Issue by hogarth-sv** [DiUS/pact-workshop-jvm#9]
I have an unauthenticated broker which is working fine with the NodeJS workshop. 

I've replaced all instances of the DiUS open pact broker, and removed the authentication properties.

The consumer is publishing the pact to my broker fine.

The provider is getting the pact from the broker.

The test is showing as completed successfully.

The broker does not show it as verified.

Has anything changed with the libraries since this was last updated?

Is there anything additional (I see no tags or versions on the provider in this test, unlike the Node one for instance) that needs to be set to publish the verification?

**Comment by uglyog** [comment]
You need to enable the `pact.verifier.publishResults` JVM system property. See https://github.com/DiUS/pact-jvm/tree/master/provider/gradle#publishing-verification-results-to-a-pact-broker
